("KERNEL.CGO"
 ("gcommon.o"
  "gstring-h.o"
  "gkernel-h.o"
  "gkernel.o"
  "pskernel.o"
  "gstring.o"
  "dgo-h.o"
  "gstate.o"
    ;; keep flutflut stuff loaded
  "flut-part.o"
  "flutflut.o"
  "target-flut.o"
  "flut-saddle-ag.go"
  "eichar-flut+0-ag.go"
 ))
